### ISSUE TITLE
Strange stats for bytes_in and bytes_out

### ISSUE THREAD

**Issue by tpitale** [ferd/vmstats#32]
On OTP 21 (in an elixir 1.8 application) and vmstats 2.3.1

We see almost all of the stats for bytes_in and bytes_out to be `2`. Just that. Every so often it'll be `1.83`.

This is similar to a behavior for `gc.count` and `reductions`.

Is this a possible bug, or does it indicate that we're not actually getting data for these keys?

**Comment by ferd** [comment]
this part of code hasn't changed in years. I don't use vmstats personally right now.
I can't say if it is a bug or if you're not getting data for these keys, but I'd say you should look into confirming you get data for these keys before anything else, because that's more likely than the metrics for GC, reductions, and bytes all breaking at once and nobody noticing for most of the year.

**Comment by tpitale** [comment]
I'll reopen if I find anything.
